import { Metadata } from "next";
import React from "react";


export const metadata: Metadata = {
  title: "New Title",
  description: "Generated by create next app",
};



function About() {
  return <div><h1>Select Sub items</h1></div>;
}

export default About;
